from db_work.services import ColorSettingsManager, LayoutRolesManager, PresentationLayoutManager, PresentationLayoutStylesManager, SlideLayoutAdditionalInfoManager, SlideLayoutDimensionsManager, SlideLayoutManager, SlideLayoutStylesManager

presentation_layout_manager = PresentationLayoutManager()
color_settings_manager = ColorSettingsManager()
presentation_layout_styles_manager = PresentationLayoutStylesManager()
slide_layout_manager = SlideLayoutManager()
layout_roles_manager = LayoutRolesManager()
slide_layout_styles_manager = SlideLayoutStylesManager()
slide_layout_additional_inf_manager = SlideLayoutAdditionalInfoManager()
slide_layout_dimensions_manager = SlideLayoutDimensionsManager()
slide_layout_additional_info = SlideLayoutAdditionalInfoManager()
